### ISSUE TITLE
Is it possible to support `DCSettingsView` for MacOS 11 ?

### ISSUE THREAD

**Issue by laike9m** [davidcaddy/DCSettings#1]
First thanks for creating this project. I found it as I'm developing a Mac app targeting MacOS 11+, and this is the only "settings UI" lib that doesn't require MacOS 12.

Though, later I found that [`DCSettingsView`](https://github.com/davidcaddy/DCSettings/blob/main/Sources/DCSettings/Views/DCSettingView.swift) still requires MacOS 12, so I can't use it in my app 😢

I'm not familiar enough with the code to tell which part is incompatible, but still I'd like to ask whether there's a slight possibility that it can support MacOS 11. Thanks in advance!

**Comment by laike9m** [comment]
Nvm, I'll write the view from scratch since it's relatively simple

**Comment by davidcaddy** [comment]
Apologies for the delayed reply @laike9m, writing your own may still be the preferred approach but it didn't take much to lower the OS requirements to macOS 11 and iOS 14, have pushed the changes with v0.3.1.
